kind: pipeline
type: docker
name: build
steps:
  image: node:10
  volumes:
    - name: npm-cache # npm 缓存挂载路径
      path: /root/.npm-cache
      commands:
        - npm install
        - npm run build
trigger:
  branch:
    - main
